# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PATH_TO_VOLUME}:/var/lib/postgresql/data
    ports:
      - 5432:5432

      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_USERNAME: ${ADMINER_DEFAULT_USERNAME}
      ADMINER_DEFAULT_PASSWORD: ${ADMINER_DEFAULT_PASSWORD}